resolver: lts-18.27
compiler: ghc-8.10.7

packages:
- . 

extra-deps:
# Required for the 8.10.1 build
#- text-format-0.3.2
#- optics-0.2
#- Diff-0.3.4
#- aeson-1.4.7.1
#- th-compat-0.1.2@sha256:3d55de1adc542c1a870c9ada90da2fbbe5f4e8bcd3eed545a55c3df9311b32a8,2854

- git: https://github.com/ucsd-progsys/liquidhaskell
  commit: 8b5e3640fe06964b27af9f6e44f563d8e6abbfe0
 
- git: https://github.com/ucsd-progsys/liquidhaskell
  commit: 8b5e3640fe06964b27af9f6e44f563d8e6abbfe0
  subdirs:
      - liquid-base
      - liquid-ghc-prim
      - liquid-containers
      - liquid-prelude

- git: https://github.com/ucsd-progsys/liquid-fixpoint
  commit: 08fa6b6e0001c2da6b96a135523ca56107a3c0d6

- git: https://github.com/facundominguez/rest
  commit: 31e974979c90e910efe5199ee0d3721b791667f6

#- git: https://github.com/well-typed/optics.git
#  commit: 0a4940cc927df3f50151692282f8b148bf326886
#  subdirs:
#    - optics-core
#    - optics-th
