# resolver: lts-18.27
# compiler: ghc-8.10.7

resolver: nightly-2022-01-06
compiler: ghc-9.0.1

packages:
- .
- ./benchrunner
- ./benchmarks/haskell
- ./prof

extra-deps:
# Required for the 8.10.1 build
#- text-format-0.3.2
#- optics-0.2
#- Diff-0.3.4
#- aeson-1.4.7.1
#- th-compat-0.1.2@sha256:3d55de1adc542c1a870c9ada90da2fbbe5f4e8bcd3eed545a55c3df9311b32a8,2854

- git: https://github.com/rrnewton/criterion-external
  commit: 201083a35e82343ae638d62711fe83185b8101d4

- git: https://github.com/ucsd-progsys/liquidhaskell
  commit: f917323a1f9db1677e592d6ffc81467d53588d70
          # ec95f39dd90857cc97cba00f68c95d39ecd5f5aa

- git: https://github.com/ucsd-progsys/liquidhaskell
  commit: f917323a1f9db1677e592d6ffc81467d53588d70
          # ec95f39dd90857cc97cba00f68c95d39ecd5f5aa
  subdirs:
      - liquid-base
      - liquid-ghc-prim
      - liquid-containers
      - liquid-prelude

- git: https://github.com/ucsd-progsys/liquid-fixpoint
  commit: 7e18f70ede589c5f7f2e0b5a3bf38250938aee28

#- git: https://github.com/ucsd-progsys/liquid-ghc-prim
#  # tag: v0.7.0
#  commit: 30a33b2d544e802d3a1f84b199d105b1488e3591

- git: https://github.com/facundominguez/liquid-base
  commit: 8ad2378cee5ccf7937d9e08aacd5c5b7128318e8

- git: https://github.com/facundominguez/rest
  commit: 31e974979c90e910efe5199ee0d3721b791667f6

#- git: https://github.com/well-typed/optics.git
#  commit: 0a4940cc927df3f50151692282f8b148bf326886
#  subdirs:
#    - optics-core
#    - optics-th
