name: Test shell.nix

# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency.
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
    paths-ignore:
      - "**/README.md"
    branches:
      - main
  pull_request:
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

jobs:
  test-nix-shell:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-25.05
    - run: nix-shell --run "cabal update && cabal build --dry-run lh-array-sort"
